### ISSUE TITLE
filename argument options

### ISSUE THREAD

**Issue by cedwards** [cedwards/saltstack-fim-module#1]
In the current release the `filename` argument writes the output to a json-formatted, gzipped file. This should be configurable:

```
fim:
  filename: /path/to/save.file
    format: json
    compress: gzip
```
